
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/koen/Jetbrains/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:199 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.5.0-21-generic - x86_64
...
